function camelcase(s) {
  return s.split(/[A-Z]/).length;
}

const s = "saveChangesInTheEditor";
console.log(camelcase(s));


// ====================
// 問題:
//   与えられた文字列がいくつの単語からできているのかを返す。
//   文字列はキャメルケースで書かれていて、最初の単語の一文字目は小文字。

// 条件:
//   s ->  文字列

// ポイント解説:
//   文字列内にある大文字で単語を区切れば単語数を求めることができる。

//   Split the s string by uppercase letters, count how many strings in the array generated by .split() method.
// ====================